language: python

python:
  - "3.6"

# Command to install dependencies
install:
  - apt install bash
  - pip install -r requirements.txt > /dev/null

# Command to run tests
script:
  - python3 test.py
