"""Module containing the strings used for command line argument parsing"""

DATA_PATH_ARG: str = '--data-path'
DATA_PATH_ARG_HELP: str = 'The path to the data to query'
EXTRACT_HANDLER_NAME: str = 'extract'
INSPECT_HANDLER_NAME: str = 'inspect'
KEY_WORDS_ARG: str = '--key-words'
KEY_WORDS_ARG_HELP: str = 'The list of key words to search for, usage: --key-words keyword1 keyword2 ...'
STORE_ACTION: str = 'store'
STORE_TRUE_ACTION: str = 'store_true'
SUB_PARSER: str = 'handler_type'
TEST_KEY_WORD1: str = 'numeric'
TEST_KEY_WORD2: str = 'Nominal'
TEST_KEY_WORD3: str = 'may'
TEST_KEY_WORD4: str = 'adas.txt'
VERBOSE_ARG: str = '--verbose'
VERBOSE_ARG_HELP: str = 'If specified, will output information in addition to CSV file paths and column names'
