"""Module containing strings for the inspect handler tests"""

CSV1_LINE1: str = 'DATA.csv'
CSV1_LINE2: str = '\tAllInt'
CSV1_LINE3: str = '\t\tMin: 2'
CSV1_LINE4: str = '\t\tMax: 200'
CSV1_LINE5: str = '\t\tRange: 198'
CSV1_LINE6: str = '\t\tMean: 42.0'
CSV1_LINE7: str = '\t\tStd: 70.8519583356734'
CSV1_LINE8: str = '\tPhase'
CSV1_LINE9: str = '\t\tAdni1: 6'
CSV1_LINE10: str = '\tTYPE'
CSV1_LINE11: str = '\t\tMaybe: 2'
CSV1_LINE12: str = '\t\tNo: 3'
CSV1_LINE13: str = '\t\tYes: 1'
CSV1_LINE14: str = '\tallTypes'
CSV1_LINE15: str = '\t\t__n-u-m-b-e-r-s__: 2'
CSV1_LINE16: str = '\t\ta-class: 3'
CSV1_LINE17: str = '\t\tnan: 1'
CSV2_LINE1: str = 'nUmeric.gz.Nominal/data/MOCA.csv'
CSV2_LINE2: str = '\tAllFloat'
CSV2_LINE3: str = '\t\tMin: -200.2'
CSV2_LINE4: str = '\t\tMax: 200.2'
CSV2_LINE5: str = '\t\tRange: 400.4'
CSV2_LINE6: str = '\t\tMean: 14.0'
CSV2_LINE7: str = '\t\tStd: 164.6573006783078'
CSV2_LINE8: str = '\tAllNaNs'
CSV2_LINE9: str = '\t\tMin: nan'
CSV2_LINE10: str = '\t\tMax: nan'
CSV2_LINE11: str = '\t\tRange: nan'
CSV2_LINE12: str = '\t\tMean: nan'
CSV2_LINE13: str = '\t\tStd: nan'
CSV2_LINE14: str = '\tIntFloat'
CSV2_LINE15: str = '\t\tMin: -16.0'
CSV2_LINE16: str = '\t\tMax: 16.0'
CSV2_LINE17: str = '\t\tRange: 32.0'
CSV2_LINE18: str = '\t\tMean: 5.25'
CSV2_LINE19: str = '\t\tStd: 15.026365717187462'
CSV3_LINE1: str = 'nomINAL/txt/adas.csv'
CSV3_LINE2: str = '\tFloatNaNs'
CSV3_LINE3: str = '\t\tMin: nan'
CSV3_LINE4: str = '\t\tMax: nan'
CSV3_LINE5: str = '\t\tRange: nan'
CSV3_LINE6: str = '\t\tMean: nan'
CSV3_LINE7: str = '\t\tStd: nan'
CSV3_LINE8: str = '\tIntNaNs'
CSV3_LINE9: str = '\t\tMin: nan'
CSV3_LINE10: str = '\t\tMax: nan'
CSV3_LINE11: str = '\t\tRange: nan'
CSV3_LINE12: str = '\t\tMean: nan'
CSV3_LINE13: str = '\t\tStd: nan'
CSV3_LINE14: str = '\tNomNaNs'
CSV3_LINE15: str = '\t\tadni: 2'
CSV3_LINE16: str = '\t\tnan: 1'
CSV3_LINE17: str = '\tmAy'
CSV3_LINE18: str = '\t\tADNI: 1'
CSV3_LINE19: str = '\t\t__n-u-m-b-e-r-s__: 2'
CSV_NOT_LOADED_LINE1: str = '\tThe CSV for this path could not be loaded due to an error of type: ' \
                           '<class \'pandas.errors.ParserError\'> and with message: Error tokenizing data. C error: ' \
                           'Expected 16 fields in line 4, saw 17\n'
CSV_NOT_LOADED_LINE2: str = '\tThe CSV for this path could not be loaded due to an error of type: ' \
                            '<class \'UnicodeDecodeError\'> and with message: \'utf-8\' codec can\'t decode byte 0x96' \
                            ' in position 0: invalid start byte'
